config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :instruments, only: [:index, :new, :create, :show] do
    resources :bookings, only: [:create, :show]
  end
  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :instrument
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :user
  has_attachment :photo
end

app/models/user.rb
class User < ApplicationRecord
  has_many :instruments, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, omniauth_providers: [:facebook]


  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception #XSS attacks
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    @instrument = Instrument.find(params[:instrument_id])
    @booking.user = current_user
    @booking.instrument = @instrument
    if @booking.save
      redirect_to instrument_booking_path(@instrument, @booking), notice: "Your bookings has been created..."
    else
      render 'instruments/show'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:search].nil? || params[:search][:name] == ""
      @instruments = Instrument.all
    else
      @instruments = Instrument.where(name: params[:search][:name])
      @message = 'We do not have that intrument.' if @instruments.empty?
    end
  end

  def show
    @instrument = Instrument.find(params[:id])
    @booking = Booking.new # This line is so we can generate a simple form for booking

  end

  def new
    @instrument = Instrument.new
  end

  def create
    @instrument = Instrument.new(instrument_params)

    if @instrument.save
      redirect_to instrument_path(@instrument)
    else
      render :new
    end
  end

  private

  def instrument_params
    params.require(:instrument).permit(:name, :price, :avaliablity, :description, :category, :photo)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@instrument, @booking], html: { class: 'form-inline' } do |f| %>
  <%= f.input :start_date, label: false, placeholder: 'Start Date', :as => :datetime_picker %>
  <%= f.input :end_date, label: false, placeholder: 'End Date', :as => :date_picker %>
  <%= f.submit class: 'search-btn' %>
<% end %>

app/views/bookings/show.html.erb
<h2>You have rented a <%= @booking.start_date %></h2>

app/views/instruments/index.erb
<div class="panel-body">
  <% @instruments.each do |instrument| %>
    <div class="row">
    <div class="col-md-7">
      <h4><%= instrument.name %></h4>
    </div>
    <%= end %>
    </div>
    </div>
<h1>hello</h1>

app/views/instruments/index.html.erb
<div class="container">
    <br><br><br><br><br>
    <h2 class="title"><span style="color:#25898b;">Discover your sound.</span></br>Rent musical instruments, equipment, and gears.</h2>


    <section class="search-form">
      <%= simple_form_for :search, url: instruments_path, method: "get", html: { class: 'form-inline' } do |f| %>
        <%= f.input :start_date, label: false, placeholder: 'Start Date', :as => :datetime_picker %>
        <%= f.input :end_date, label: false, placeholder: 'End Date', :as => :date_picker %>
        <%= f.input :name, input_html: { class: 'search-input' }, label: false, placeholder: "What instrument are you looking for?" %>
        <%= f.submit class: 'search-btn' %>
      <% end %>
    </section>
    <br><br>

    <section class="gallery">
      <div class="row">
        <% @instruments.each do |instrument| %>
          <div class="col-xs-4">
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path instrument.photo.path %>);">
              <%= link_to instrument_path(instrument), class: 'card-link' do %><% end %>
              <div class="card-category"><%= instrument.name %></div>
              <div class="card-description">
                <p> <%= "$ #{instrument.price}" %> </p>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <% if @message %>
        <br>
        <br>
        <br>
        <p> <%= @message %> </p>
      <% end %>

    </section>
</div>

app/views/instruments/show.html.erb
<div class="container">
  <br><br><br><br><br>

  <div class="card card-show-page" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= cl_image_path @instrument.photo.path %>);">
    <div class="card-category"><%= @instrument.name %></div>
    <div class="card-description">
      <p> <%= "$ #{@instrument.price}" %> </p>
    </div>
  </div>

  <br><br><br>

  <%= render 'bookings/form' %>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <title> Rent musical instruments, equipment, and gears.</title>
    <link rel="icon" type="image/jpg" href="https://s5.postimg.org/qqgj4taev/logo.png">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  </head>
   <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= javascript_include_tag 'application' %>
    <%= yield(:after_js) %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= f.input :photo, as: :attachinary %>

app/views/pages/home.html.erb
<!--banner-->
    <div class="jumbotron text-center">
      <div class="container">
          <div class="row">
             <h3>Rent instruments, equipment, and space on MusicBiz.</h3>
              <%= link_to 'Learn more', instruments_path, class: 'btn-home' %>
          </div>
      </div>
    </div>
<!--main section-->
    <div class="tite-home-page">
      <p id="featured_categories">
        Featured Categories
      </p>
    </div>
    <div class="container">
       <div class="row">
          <div class="col-xs-12 col-sm-4">
            <div class="card card-guitar">
              <div class="card-description">
                <h2>Guitar</h2>
              </div>
              <%= link_to instruments_path(search: { name: 'guitar' }), class: 'card-link' do %>
              <% end %>
            </div>
         </div>
          <div class="col-xs-12 col-sm-4">
            <div class="card card-piano">
              <div class="card-description">
                <h2>Piano</h2>
              </div>

              <%= link_to instruments_path(search: { name: 'piano' }), class: 'card-link' do %><% end %>
            </div>
          </div>
          <div class="col-xs-12 col-sm-4">
            <div class="card card-drums">
              <div class="card-description">
                <h2>Drums</h2>
              </div>
              <%= link_to instruments_path(search: { name: 'drums' }), class: 'card-link' do %><% end %>
            </div>
          </div>
          <br>
          <div class="col-xs-12 col-sm-4">
            <div class="card card-bass">
              <div class="card-description">
                <h2>Bass</h2>
              </div>
              <%= link_to instruments_path(search: { name: 'bass' }), class: 'card-link' do %><% end %>
            </div>
         </div>
          <div class="col-xs-12 col-sm-4">
            <div class="card card-brass">
              <div class="card-description">
                <h2>Brass</h2>
              </div>
              <%= link_to instruments_path(search: { name: 'brass' }), class: 'card-link' do %><% end %>
            </div>
          </div>
          <div class="col-xs-12 col-sm-4">
            <div class="card card-string">
              <div class="card-description">
                <h2>String</h2>
              </div>
              <%= link_to instruments_path(search: { name: 'string' }), class: 'card-link' do %><% end %>
            </div>
          </div>
      </div>
    </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="main-footer">
  <div class="footer-container">
    <div class="footer-sections">
      <section class="airbnb">
        <ul>
          <li class="list_title">MusicBiz</li>
          <li><a href="#">About</a></li>
          <li><a href="#">Careers</a></li>
          <li><a href="#">Press</a></li>
          <li><a href="#">Policies</a></li>
          <li><a href="#">Help</a></li>
        </ul>
      </section>
      <section class="discover">
        <ul>
          <li class="list_title">Discover</li>
          <li><a href="#">FAQ</a></li>
          <li><a href="#">Trust & Safety</a></li>
          <li><a href="#">Gift Cards</a></li>
          <li><a href="#">Guidebooks</a></li>
          <li><a href="#">How it Works</a></li>
        </ul>
      </section>
      <section class="Hosting">
        <ul>
          <li class="list_title">Information</li>
          <li><a href="#">Site Map</a></li>
          <li><a href="#">Terms and Privacy</a></li>
          <li><a href="#">Trust & Security</a></li>
          <li><a href="#">Cancellation Policy</a></li>
        </ul>
      </section>
    </div>
    <footer class="footer-footer">
      <span><i class="fa fa-airbnb"></i>&copy; musicbinz</span>
      <ul>
        <li><a href=""><i class="fa fa-facebook fa-2x"></i></a></li>
        <li><a href=""><i class="fa fa-linkedin fa-2x"></i></a></li>
        <li><a href=""><i class="fa fa-twitter fa-2x"></i></a></li>
        <li><a href=""><i class="fa fa-youtube fa-2x"></i></a></li>
      </ul>
    </footer>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <div class="logo">
    <div class="equalizer">
      <span class="bar bar-1"></span>
      <span class="bar bar-2"></span>
      <span class="bar bar-3"></span>
      <span class="bar bar-4"></span>
    </div>
    <div class="equalizer second">
      <span class="bar bar-1"></span>
      <span class="bar bar-2"></span>
      <span class="bar bar-3"></span>
      <span class="bar bar-4"></span>
    </div>
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
       <p>musicbiz</p>

  <% end %>
</div>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <%= link_to "Create Listing",class: "navbar-wagon-link" %>
      <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Rentals", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "http://placehold.it/30x30" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Dashbord") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Create Listing",omniauth_authorize_path(:user, :facebook), class: "navbar-wagon-item navbar-wagon-link create-a-listing" %>
      <%= link_to t(".registrations", default: "Sign Up"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Create Listing</a></li>
        <li><a href="#">Sign Up</a></li>
        <li><a href="#">Log In</a></li>
      </ul>
    </div>
  </div>
</div>